version: "2"
services:
  proxy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  server:
    privileged: true
    build:
      context: ./interaction_node
      dockerfile: Dockerfile
    ports:
      - "1995:1995"
      - "1235:1235/udp"
    depends_on:
      - proxy
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count : 1
              capabilities: [gpu]
