version: "3"
services:
  proxy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  server:
    build:
      context: ./interaction_node
      dockerfile: Dockerfile
    ports:
      - "1995:1995"
      - "1235:1235/udp"
    depends_on:
      - proxy
  protos:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "./protos.sh"
  shell:
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/sh -c "./start-camera.sh"
