version: "3"
services:
  proxy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  server:
    privileged: true
    build:
      context: ./visualInputNode
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8888:8888"

    depends_on:
      - proxy
