version: "3"
services:
  proxy:
    build:
      context: ./envoy
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  server:
    build:
      context: ./interaction_node
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - proxy
