/**
 * @fileoverview gRPC-Web generated client stub for visualInputNode
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.12.4
// source: protos/visualInputNode.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as protos_visualInputNode_pb from '../protos/visualInputNode_pb';


export class VisualInputNodeServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorInitializeVisualInputNode = new grpcWeb.MethodDescriptor(
    '/visualInputNode.VisualInputNodeService/InitializeVisualInputNode',
    grpcWeb.MethodType.UNARY,
    protos_visualInputNode_pb.InitializeVisualInputNodeRequest,
    protos_visualInputNode_pb.InitializeVisualInputNodeResponse,
    (request: protos_visualInputNode_pb.InitializeVisualInputNodeRequest) => {
      return request.serializeBinary();
    },
    protos_visualInputNode_pb.InitializeVisualInputNodeResponse.deserializeBinary
  );

  initializeVisualInputNode(
    request: protos_visualInputNode_pb.InitializeVisualInputNodeRequest,
    metadata: grpcWeb.Metadata | null): Promise<protos_visualInputNode_pb.InitializeVisualInputNodeResponse>;

  initializeVisualInputNode(
    request: protos_visualInputNode_pb.InitializeVisualInputNodeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: protos_visualInputNode_pb.InitializeVisualInputNodeResponse) => void): grpcWeb.ClientReadableStream<protos_visualInputNode_pb.InitializeVisualInputNodeResponse>;

  initializeVisualInputNode(
    request: protos_visualInputNode_pb.InitializeVisualInputNodeRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: protos_visualInputNode_pb.InitializeVisualInputNodeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/visualInputNode.VisualInputNodeService/InitializeVisualInputNode',
        request,
        metadata || {},
        this.methodDescriptorInitializeVisualInputNode,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/visualInputNode.VisualInputNodeService/InitializeVisualInputNode',
    request,
    metadata || {},
    this.methodDescriptorInitializeVisualInputNode);
  }

}

