# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sceneCapture.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12sceneCapture.proto\x12\x0csceneCapture\"\x1f\n\x1dInitializeSceneCaptureRequest\"8\n\x1eInitializeSceneCaptureResponse\x12\x16\n\x0eis_initialized\x18\x01 \x01(\x08\")\n\x11RunCaptureRequest\x12\x14\n\x0c\x63\x61pture_name\x18\x01 \x01(\t\"\x14\n\x12RunCaptureResponse\"\x14\n\x12StopCaptureRequest\"\x15\n\x13StopCaptureResponse2\xaf\x02\n\x13SceneCaptureService\x12s\n\x16InitializeSceneCapture\x12+.sceneCapture.InitializeSceneCaptureRequest\x1a,.sceneCapture.InitializeSceneCaptureResponse\x12O\n\nRunCapture\x12\x1f.sceneCapture.RunCaptureRequest\x1a .sceneCapture.RunCaptureResponse\x12R\n\x0bStopCapture\x12 .sceneCapture.StopCaptureRequest\x1a!.sceneCapture.StopCaptureResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sceneCapture_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INITIALIZESCENECAPTUREREQUEST._serialized_start=36
  _INITIALIZESCENECAPTUREREQUEST._serialized_end=67
  _INITIALIZESCENECAPTURERESPONSE._serialized_start=69
  _INITIALIZESCENECAPTURERESPONSE._serialized_end=125
  _RUNCAPTUREREQUEST._serialized_start=127
  _RUNCAPTUREREQUEST._serialized_end=168
  _RUNCAPTURERESPONSE._serialized_start=170
  _RUNCAPTURERESPONSE._serialized_end=190
  _STOPCAPTUREREQUEST._serialized_start=192
  _STOPCAPTUREREQUEST._serialized_end=212
  _STOPCAPTURERESPONSE._serialized_start=214
  _STOPCAPTURERESPONSE._serialized_end=235
  _SCENECAPTURESERVICE._serialized_start=238
  _SCENECAPTURESERVICE._serialized_end=541
# @@protoc_insertion_point(module_scope)
