export const MESH_TRANSFORM = {
  MORPH: "MORPH",
  CUSTOM_ATTRIBUTES: "CUSTOM_ATTRIBUTES",
  DEFAULT: "DEFAULT",
  PRE_DEFINED: "PRE_DEFINED",
};

export const CUSTOM_BUFFER_GEOMETRY_TYPES = {
  QUAD: "QUAD",
  EMPTY: "EMPTY",
};
export const CUSTOM_GEOMETRY_TYPES = [
  CUSTOM_BUFFER_GEOMETRY_TYPES.QUAD,
  CUSTOM_BUFFER_GEOMETRY_TYPES.EMPTY,
];
