export enum MESH_TRANSFORM {
  MORPH = "MORPH",
  CUSTOM_ATTRIBUTES = "CUSTOM_ATTRIBUTES",
  DEFAULT = "DEFAULT",
}

export const CUSTOM_BUFFER_GEOMETRY_TYPES = {
  QUAD: "QUAD",
};
export const CUSTOM_GEOMETRY_TYPES = [CUSTOM_BUFFER_GEOMETRY_TYPES.QUAD];
