/**
 * @fileoverview gRPC-Web generated client stub for interactionNode
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.12.4
// source: protos/interactionNode.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as protos_interactionNode_pb from '../protos/interactionNode_pb';


export class InteractionNodeServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorInitializeInteractionNode = new grpcWeb.MethodDescriptor(
    '/interactionNode.InteractionNodeService/InitializeInteractionNode',
    grpcWeb.MethodType.UNARY,
    protos_interactionNode_pb.InitializeInteractionNodeRequest,
    protos_interactionNode_pb.InitializeInteractionNodeResponse,
    (request: protos_interactionNode_pb.InitializeInteractionNodeRequest) => {
      return request.serializeBinary();
    },
    protos_interactionNode_pb.InitializeInteractionNodeResponse.deserializeBinary
  );

  initializeInteractionNode(
    request: protos_interactionNode_pb.InitializeInteractionNodeRequest,
    metadata: grpcWeb.Metadata | null): Promise<protos_interactionNode_pb.InitializeInteractionNodeResponse>;

  initializeInteractionNode(
    request: protos_interactionNode_pb.InitializeInteractionNodeRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: protos_interactionNode_pb.InitializeInteractionNodeResponse) => void): grpcWeb.ClientReadableStream<protos_interactionNode_pb.InitializeInteractionNodeResponse>;

  initializeInteractionNode(
    request: protos_interactionNode_pb.InitializeInteractionNodeRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: protos_interactionNode_pb.InitializeInteractionNodeResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/interactionNode.InteractionNodeService/InitializeInteractionNode',
        request,
        metadata || {},
        this.methodDescriptorInitializeInteractionNode,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/interactionNode.InteractionNodeService/InitializeInteractionNode',
    request,
    metadata || {},
    this.methodDescriptorInitializeInteractionNode);
  }

}

