export const ANIMATION_LOOP_TYPES = {
  ONE_TO_ONE: "ONE_TO_ONE",
  ZERO_TO_ONE: "ZERO_TO_ONE",
  ZERO_TO_ZERO: "ZERO_TO_ZERO",
};

export const DEFAULT_DURATION_SECONDS = 10;
export const DEFAULT_STEEPNESS = 1;
