# syntax=docker/dockerfile:1

FROM python:3
WORKDIR /visualInputNode

 COPY requirements.txt requirements.txt
 RUN pip install --upgrade pip setuptools
 RUN pip install -r requirements.txt


WORKDIR /visualInputNode

COPY . .
RUN chmod +x visualInputNode.py
CMD ["python3", "visualInputNode.py"]
