# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/visualInputNode.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cprotos/visualInputNode.proto\x12\x0fvisualInputNode\x1a\x1cgoogle/api/annotations.proto\"\"\n InitializeVisualInputNodeRequest\":\n!InitializeVisualInputNodeResponse\x12\x15\n\risInitialized\x18\x01 \x01(\x08\x32\x9d\x01\n\x16VisualInputNodeService\x12\x82\x01\n\x19InitializeVisualInputNode\x12\x31.visualInputNode.InitializeVisualInputNodeRequest\x1a\x32.visualInputNode.InitializeVisualInputNodeResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.visualInputNode_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INITIALIZEVISUALINPUTNODEREQUEST._serialized_start=79
  _INITIALIZEVISUALINPUTNODEREQUEST._serialized_end=113
  _INITIALIZEVISUALINPUTNODERESPONSE._serialized_start=115
  _INITIALIZEVISUALINPUTNODERESPONSE._serialized_end=173
  _VISUALINPUTNODESERVICE._serialized_start=176
  _VISUALINPUTNODESERVICE._serialized_end=333
# @@protoc_insertion_point(module_scope)
